import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class MainWidget(object):
    def setup_window_roller(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(10, 15, 10, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.SavedLineFinished = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHeightForWidth(self.SavedLineFinished.sizePolicy().hasHeightForWidth())
        self.SavedLineFinished.setSizePolicy(sizePolicy)
        self.SavedLineFinished.setObjectName("SavedLineFinished")
        self.gridLayout.addWidget(self.SavedLineFinished, 1, 1, 1, 1)
        self.SavedLine0 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHeightForWidth(self.SavedLine0.sizePolicy().hasHeightForWidth())
        self.SavedLine0.setSizePolicy(sizePolicy)
        self.SavedLine0.setObjectName("SavedLine0")
        self.gridLayout.addWidget(self.SavedLine0, 1, 0, 1, 1)
        self.Savebutton0 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Savebutton0.setObjectName("Savebutton0")
        self.gridLayout.addWidget(self.Savebutton0, 1, 2, 1, 1)
        self.Addbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Addbutton.setObjectName("Addbutton")
        self.gridLayout.addWidget(self.Addbutton, 0, 2, 1, 1)
        self.AddLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.AddLine.setObjectName("AddLine")
        self.gridLayout.addWidget(self.AddLine, 0, 0, 1, 1)
        self.AddLine_blank = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHeightForWidth(self.AddLine_blank.sizePolicy().hasHeightForWidth())
        self.AddLine_blank.setSizePolicy(sizePolicy)
        self.AddLine_blank.setObjectName("AddLine_blank")
        self.gridLayout.addWidget(self.AddLine_blank, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Savebutton0.setText(_translate("MainWindow", "Save"))
        self.Addbutton.setText(_translate("MainWindow", "AddButton"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MainWidget()
    ui.setup_window_roller(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
